### PR TITLE
added localMusic.html and updated code

### PR DESCRIPTION
**Pull request by Trevis-Williams**

### CODE REVIEW

**Review by CalmedDuck — APPROVED** [review]
Great work.

**Review by CrisCo116 — COMMENTED** [review]
looks good.

**Review by CrisCo116 — COMMENTED** [review]
looks good

**Review by CrisCo116 — COMMENTED** [review]
looks good

**Comment by Rounderr21** [comment]
lookinnnnn gooood

**Review by CrisCo116 — APPROVED** [review]
look really good

**Pull request merged**
